-- MySQL Script generated by MySQL Workbench
-- 04/27/15 02:49:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BayiDenetim
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BayiDenetim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BayiDenetim` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `BayiDenetim` ;

-- -----------------------------------------------------
-- Table `BayiDenetim`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BayiDenetim`.`Company` (
  `cID` INT NOT NULL AUTO_INCREMENT,
  `cName` VARCHAR(45) NULL,
  `cAddress` VARCHAR(255) NULL,
  `cFax` VARCHAR(45) NULL,
  `cPhone` VARCHAR(45) NULL,
  PRIMARY KEY (`cID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BayiDenetim`.`CompanyOfficer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BayiDenetim`.`CompanyOfficer` (
  `coID` INT NOT NULL AUTO_INCREMENT,
  `coName` VARCHAR(45) NULL,
  `coPass` VARCHAR(45) NULL,
  `coEmail` VARCHAR(45) NULL,
  `fk_cID` INT NULL,
  PRIMARY KEY (`coID`),
  INDEX `fk_CompanyOfficer_Company_idx` (`fk_cID` ASC),
  CONSTRAINT `fk_CompanyOfficer_Company`
    FOREIGN KEY (`fk_cID`)
    REFERENCES `BayiDenetim`.`Company` (`cID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BayiDenetim`.`Dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BayiDenetim`.`Dealer` (
  `dID` INT NOT NULL AUTO_INCREMENT,
  `dName` VARCHAR(45) NULL,
  `dAddress` VARCHAR(45) NULL,
  `dRating` DOUBLE NULL,
  `fk_cID` INT NULL,
  `dTabletKey` VARCHAR(255) NULL,
  `dTabletPass` VARCHAR(255) NULL,
  PRIMARY KEY (`dID`),
  INDEX `fk_Dealer_Company1_idx` (`fk_cID` ASC),
  CONSTRAINT `fk_Dealer_Company1`
    FOREIGN KEY (`fk_cID`)
    REFERENCES `BayiDenetim`.`Company` (`cID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BayiDenetim`.`Form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BayiDenetim`.`Form` (
  `fID` INT NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NULL,
  `fType` VARCHAR(45) NULL,
  `fk_cID` INT NULL,
  PRIMARY KEY (`fID`),
  INDEX `fk_Form_Company1_idx` (`fk_cID` ASC),
  CONSTRAINT `fk_Form_Company1`
    FOREIGN KEY (`fk_cID`)
    REFERENCES `BayiDenetim`.`Company` (`cID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BayiDenetim`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BayiDenetim`.`Question` (
  `qID` INT NOT NULL AUTO_INCREMENT,
  `qText` VARCHAR(255) NULL,
  `fk_fID` INT NULL,
  PRIMARY KEY (`qID`),
  INDEX `fk_Question_Form1_idx` (`fk_fID` ASC),
  CONSTRAINT `fk_Question_Form1`
    FOREIGN KEY (`fk_fID`)
    REFERENCES `BayiDenetim`.`Form` (`fID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BayiDenetim`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BayiDenetim`.`Answer` (
  `aID` INT NOT NULL AUTO_INCREMENT,
  `aText` VARCHAR(45) NULL,
  `fk_qID` INT NULL,
  `aCount` INT NULL DEFAULT 0,
  PRIMARY KEY (`aID`),
  INDEX `fk_Answer_Question1_idx` (`fk_qID` ASC),
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`fk_qID`)
    REFERENCES `BayiDenetim`.`Question` (`qID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
